// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartSpace.API.Data;

#nullable disable

namespace SmartSpace.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartSpace.API.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "tenant@smartspace.com",
                            FullName = "John Tenant",
                            PasswordHash = "$2a$11$nS4SgyZulvENEj4BiLl8x.6MU2HjnaPPLYuaiHQH8iCHlOkDPpDqi",
                            Role = "Tenant"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "manager@smartspace.com",
                            FullName = "Sarah PropertyManager",
                            PasswordHash = "$2a$11$nS4SgyZulvENEj4BiLl8x.6MU2HjnaPPLYuaiHQH8iCHlOkDPpDqi",
                            Role = "PropertyManager"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "technician@smartspace.com",
                            FullName = "Alex Technician",
                            PasswordHash = "$2a$11$nS4SgyZulvENEj4BiLl8x.6MU2HjnaPPLYuaiHQH8iCHlOkDPpDqi",
                            Role = "Technician"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "inventory@smartspace.com",
                            FullName = "Morgan InventoryOfficer",
                            PasswordHash = "$2a$11$nS4SgyZulvENEj4BiLl8x.6MU2HjnaPPLYuaiHQH8iCHlOkDPpDqi",
                            Role = "InventoryOfficer"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
