"""
SmartSpace - Inventory Search Agent Payload & Validation Test Suite
Designed for SE3090 Assignment 2 & Quality Management Viva requirements.

Validates:
1. Serialization/Deserialization of the C# ASP.NET Core API JSON request payload into Pydantic contracts.
2. Boundary conditions: Max 5 candidates, min 1 stock, non-negative unit costs.
3. Invalid payloads: Malformed UUIDs, blank repair steps, negative stock quantities.
4. Deterministic AI validation: Cross-checks AI proposed items against database candidate parts
   to prevent AI hallucinations, price tampering, duplicate items, and over-allocation.
"""

import json
from decimal import Decimal
from uuid import UUID, uuid4
import pytest
from pydantic import ValidationError

from core.errors import AiServiceError
from schemas.contracts import (
    InventoryCandidate,
    InventorySearchRequest,
    InventorySearchResult,
    ProposedInventoryItem,
)
from validation.agent_results import validate_inventory


# =============================================================================
# FIXTURES & CANONICAL C# PAYLOAD SAMPLES
# =============================================================================

@pytest.fixture
def sample_csharp_api_payload() -> dict:
    """
    Simulates the exact JSON payload generated by the ASP.NET Core 8 Web API
    when invoking the LangGraph Inventory Search Agent.
    """
    return {
        "ticket_id": "7f8c0571-066b-4e09-b6bb-fdf5b4b1a41b",
        "normalized_description": "Water leaking from bathroom sink mixer valve and supply line",
        "trade_required": "Plumber",
        "planned_steps": [
            "Turn off the isolation valve under the sink",
            "Disassemble the sink mixer tap assembly",
            "Replace defective rubber washer and Teflon seal"
        ],
        "candidates": [
            {
                "item_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
                "item_name": "Rubber Tap Washer 0.5-inch",
                "category": "Plumbing",
                "available_stock": 25,
                "unit_cost": "150.00"
            },
            {
                "item_id": "8bb2f1c8-2d54-41d3-8fb1-9c60dfd2e389",
                "item_name": "Teflon Thread Seal Tape (12m)",
                "category": "Plumbing",
                "available_stock": 40,
                "unit_cost": "85.00"
            }
        ]
    }


# =============================================================================
# 1. C# API PAYLOAD SERIALIZATION & SCHEMA TESTS
# =============================================================================

def test_csharp_payload_deserializes_successfully(sample_csharp_api_payload):
    """
    VIVA PREP:
    What it does: Validates that JSON generated by C# ASP.NET Core deserializes into InventorySearchRequest.
    Why written: Confirms contract compatibility across the C# <-> Python microservice boundary.
    """
    json_str = json.dumps(sample_csharp_api_payload)
    request = InventorySearchRequest.model_validate_json(json_str)

    assert request.ticket_id == UUID("7f8c0571-066b-4e09-b6bb-fdf5b4b1a41b")
    assert request.trade_required == "Plumber"
    assert len(request.planned_steps) == 3
    assert len(request.candidates) == 2

    # Verify first candidate fields and types
    first_candidate = request.candidates[0]
    assert first_candidate.item_name == "Rubber Tap Washer 0.5-inch"
    assert first_candidate.available_stock == 25
    assert first_candidate.unit_cost == Decimal("150.00")


def test_candidates_boundary_accepts_exactly_five_candidates(sample_csharp_api_payload):
    """
    VIVA PREP:
    What it does: Boundary test ensuring exactly 5 candidate items (the contract maximum) is accepted.
    Why written: In LangGraph, candidates are limited to top 5 to fit LLM token context efficiently.
    """
    five_candidates = [
        {
            "item_id": str(uuid4()),
            "item_name": f"Part #{i}",
            "category": "Plumbing",
            "available_stock": 10 + i,
            "unit_cost": f"{100 + i}.00"
        }
        for i in range(5)
    ]
    sample_csharp_api_payload["candidates"] = five_candidates

    request = InventorySearchRequest.model_validate(sample_csharp_api_payload)
    assert len(request.candidates) == 5


def test_candidates_boundary_rejects_more_than_five_candidates(sample_csharp_api_payload):
    """
    VIVA PREP:
    What it does: Boundary failure test when C# API passes 6 candidates (> 5).
    Why written: Protects prompt token budgets and enforces system-wide contract invariant.
    """
    six_candidates = [
        {
            "item_id": str(uuid4()),
            "item_name": f"Part #{i}",
            "category": "Plumbing",
            "available_stock": 5,
            "unit_cost": "200.00"
        }
        for i in range(6)
    ]
    sample_csharp_api_payload["candidates"] = six_candidates

    with pytest.raises(ValidationError) as exc_info:
        InventorySearchRequest.model_validate(sample_csharp_api_payload)

    assert "candidates" in str(exc_info.value)


def test_candidate_rejects_zero_or_negative_stock(sample_csharp_api_payload):
    """
    VIVA PREP:
    What it does: Validates that candidate parts with available_stock <= 0 are rejected by the schema.
    Why written: The AI agent should only receive parts that have stock available (ge=1).
    """
    sample_csharp_api_payload["candidates"][0]["available_stock"] = 0

    with pytest.raises(ValidationError) as exc_info:
        InventorySearchRequest.model_validate(sample_csharp_api_payload)

    assert "available_stock" in str(exc_info.value)


def test_payload_rejects_malformed_uuid(sample_csharp_api_payload):
    """
    VIVA PREP:
    What it does: Tests invalid GUID/UUID string rejection.
    Why written: Ensures invalid database keys sent from API are stopped before reaching the LLM agent.
    """
    sample_csharp_api_payload["ticket_id"] = "invalid-guid-format-xyz"

    with pytest.raises(ValidationError) as exc_info:
        InventorySearchRequest.model_validate(sample_csharp_api_payload)

    assert "ticket_id" in str(exc_info.value)


def test_payload_rejects_invalid_trade_specialty(sample_csharp_api_payload):
    """
    VIVA PREP:
    What it does: Validates that trade_required must strictly be one of the canonical trades ("Plumber", "Electrician", "Handyman").
    Why written: Protects against out-of-scope trades and enforces system enum boundaries.
    """
    sample_csharp_api_payload["trade_required"] = "Astronaut"

    with pytest.raises(ValidationError) as exc_info:
        InventorySearchRequest.model_validate(sample_csharp_api_payload)

    assert "trade_required" in str(exc_info.value)


def test_payload_rejects_negative_unit_cost(sample_csharp_api_payload):
    """
    VIVA PREP:
    What it does: Validates NonNegativeDecimal constraint on candidate unit cost.
    Why written: Prevents negative unit costs which could lead to billing exploits or inventory errors.
    """
    sample_csharp_api_payload["candidates"][0]["unit_cost"] = "-50.00"

    with pytest.raises(ValidationError) as exc_info:
        InventorySearchRequest.model_validate(sample_csharp_api_payload)

    assert "unit_cost" in str(exc_info.value)


def test_payload_rejects_unrecognized_extra_fields(sample_csharp_api_payload):
    """
    VIVA PREP:
    What it does: Tests strict contract schema with extra='forbid'.
    Why written: Enforces zero tolerance for injected, unexpected, or unvalidated payload properties.
    """
    sample_csharp_api_payload["malicious_injected_payload"] = "DROP TABLE Inventory;"

    with pytest.raises(ValidationError) as exc_info:
        InventorySearchRequest.model_validate(sample_csharp_api_payload)

    assert "extra_forbidden" in str(exc_info.value)


# =============================================================================
# 2. DETERMINISTIC AI VALIDATION TESTS (Anti-Hallucination Guardrails)
# =============================================================================

def test_deterministic_validation_accepts_valid_proposed_parts():
    """
    VIVA PREP:
    What it does: Verifies happy-path deterministic validation when AI proposes allow-listed parts.
    Why written: Demonstrates normal completion of the Inventory Search Agent.
    """
    item_id = uuid4()
    candidate = InventoryCandidate(
        item_id=item_id,
        item_name="Brass Ball Valve 1-inch",
        category="Plumbing",
        available_stock=8,
        unit_cost=Decimal("1250.00")
    )

    ai_result = InventorySearchResult(
        inventory_items=[
            ProposedInventoryItem(
                item_id=item_id,
                item_name="Brass Ball Valve 1-inch",
                quantity=2, # <= 8 available
                unit_cost=Decimal("1250.00"),
                subtotal=Decimal("2500.00") # 2 * 1250
            )
        ],
        estimated_parts_cost=Decimal("2500.00"),
        confidence_score=Decimal("0.95")
    )

    # Should not raise any error
    validate_inventory(ai_result, [candidate])


def test_deterministic_validation_rejects_hallucinated_part_id():
    """
    VIVA PREP:
    What it does: Security test checking that AI cannot invent/hallucinate new part IDs.
    Why written: High quality risk in LLMs. AI must strictly pick from candidate parts passed from C# database.
    """
    trusted_id = uuid4()
    candidate = InventoryCandidate(
        item_id=trusted_id,
        item_name="PVC Glue 250ml",
        category="Plumbing",
        available_stock=10,
        unit_cost=Decimal("350.00")
    )

    fake_id = uuid4() # AI invented this UUID
    ai_result = InventorySearchResult(
        inventory_items=[
            ProposedInventoryItem(
                item_id=fake_id,
                item_name="PVC Glue 250ml",
                quantity=1,
                unit_cost=Decimal("350.00"),
                subtotal=Decimal("350.00")
            )
        ],
        estimated_parts_cost=Decimal("350.00"),
        confidence_score=Decimal("0.8")
    )

    with pytest.raises(AiServiceError, match="not allow-listed"):
        validate_inventory(ai_result, [candidate])


def test_deterministic_validation_rejects_quantity_exceeding_stock():
    """
    VIVA PREP:
    What it does: Tests that AI cannot propose quantities greater than available warehouse stock.
    Why written: Prevents recommending parts that cannot be fulfilled.
    """
    item_id = uuid4()
    candidate = InventoryCandidate(
        item_id=item_id,
        item_name="Water Pump Impeller",
        category="Plumbing",
        available_stock=2, # Only 2 available
        unit_cost=Decimal("3200.00")
    )

    ai_result = InventorySearchResult(
        inventory_items=[
            ProposedInventoryItem(
                item_id=item_id,
                item_name="Water Pump Impeller",
                quantity=5, # Requested 5 > 2 available!
                unit_cost=Decimal("3200.00"),
                subtotal=Decimal("16000.00")
            )
        ],
        estimated_parts_cost=Decimal("16000.00"),
        confidence_score=Decimal("0.85")
    )

    with pytest.raises(AiServiceError, match="quantity is invalid"):
        validate_inventory(ai_result, [candidate])


def test_deterministic_validation_rejects_altered_unit_cost():
    """
    VIVA PREP:
    What it does: Tests that AI cannot modify unit price (e.g. prompt injection attack or hallucination).
    Why written: Prevents financial loss and enforces database-authoritative pricing.
    """
    item_id = uuid4()
    candidate = InventoryCandidate(
        item_id=item_id,
        item_name="Circuit Breaker 32A",
        category="Electrical",
        available_stock=15,
        unit_cost=Decimal("1500.00") # Official price: 1500
    )

    ai_result = InventorySearchResult(
        inventory_items=[
            ProposedInventoryItem(
                item_id=item_id,
                item_name="Circuit Breaker 32A",
                quantity=1,
                unit_cost=Decimal("500.00"), # AI altered price to 500!
                subtotal=Decimal("500.00")
            )
        ],
        estimated_parts_cost=Decimal("500.00"),
        confidence_score=Decimal("0.9")
    )

    with pytest.raises(AiServiceError, match="do not match trusted data"):
        validate_inventory(ai_result, [candidate])


def test_deterministic_validation_rejects_subtotal_math_error():
    """
    VIVA PREP:
    What it does: Validates that arithmetic calculations (quantity * unit_cost = subtotal) are verified deterministically.
    Why written: LLMs are prone to arithmetic errors. Software engineering validation guarantees financial accuracy.
    """
    item_id = uuid4()
    candidate = InventoryCandidate(
        item_id=item_id,
        item_name="Electrical Cable 2.5mm (10m)",
        category="Electrical",
        available_stock=20,
        unit_cost=Decimal("450.00")
    )

    ai_result = InventorySearchResult(
        inventory_items=[
            ProposedInventoryItem(
                item_id=item_id,
                item_name="Electrical Cable 2.5mm (10m)",
                quantity=2,
                unit_cost=Decimal("450.00"),
                subtotal=Decimal("800.00") # Incorrect arithmetic: 2 * 450 should be 900
            )
        ],
        estimated_parts_cost=Decimal("800.00"),
        confidence_score=Decimal("0.9")
    )

    with pytest.raises(AiServiceError, match="subtotal is invalid"):
        validate_inventory(ai_result, [candidate])
